### ISSUE TITLE
Speed up lock manager during bulk operations

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#33]
As suggested in [this thread](https://community.cryptomator.org/t/still-performance-issues-in-1-4-6/3311/2?u=overheadhunter), there might be room for improvements in the locking scheme implemented in #15:

Since the _modification_ of the _directory resource_ happens atomically when actually adding/removing a child, it might be worth trying to only get a _shared read lock_ on a directory when adding or removing children. This is more of a _eventual consistency_ model. I.e. a concurrent directory listing will be undefined.

When creating, deleting or moving a directory, we still need an _exclusive write lock_ on that directory. During that time no read lock can be obtained, thus modifications to ancestors will not be possible.

### Todo
- [x] profile application while adding a single large directory (deeply nested)
- [x] decide whether lock contention can be reduced on directory locks
- [x] ~~(optionally) only read-lock directories when adding or removing children~~

**Comment by overheadhunter** [comment]
I added a directory `a/b/c/d/e` containing 500 4-byte-files. The work was done by 5 FUSE threads, all behaving similar. We see that the actual locking isn't taking much time, but the recursion does:

![Bildschirmfoto 2019-03-25 um 16 57 29](https://user-images.githubusercontent.com/1204330/54935015-c63d5700-4f1f-11e9-9e11-fcf5dca99245.png)

**Comment by overheadhunter** [comment]
Lock contention is not a problem.

However, the locking mechanism could be sped up significantly by reducing conversions between `List<String> pathComponents` and `String path`:

![Bildschirmfoto 2019-03-26 um 09 33 21](https://user-images.githubusercontent.com/1204330/54982234-a30bb980-4faa-11e9-8af2-23b2932a6cfa.png)

We now have more than 10k invocations in 927ms, where we had 5.5k before in 986ms before.
